version: '3.4'

services:
  new-api:
    image: registry.cn-hangzhou.aliyuncs.com/hcyj-newapi/hcyj-new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3050:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=new-api:ixTFwcsAyx2iYwwj@tcp(host.docker.internal:3306)/new-api
      - REDIS_CONN_STRING=redis://host.docker.internal:6379/4
      - TZ=Asia/Shanghai
      - BATCH_UPDATE_ENABLED=true
      - SESSION_SECRET=random_string
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3050/api/status | grep -o '\"success\":\\s*true' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3